name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set build tag as env var
        run: echo "TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gogeizhalsbot:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/gogeizhalsbot:${{ env.TAG }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gogeizhalsbot --all-tags
